plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

repositories {
    google()
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

android {
    namespace 'com.dd.v2ray'
    compileSdk 33

    defaultConfig {
        applicationId "com.dd.v2ray"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    sourceSets {
        main {
            java.srcDirs = ['src/main/kotlin', 'src/main/java']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

// Bypass pemeriksaan AAR metadata
tasks.whenTaskAdded { task ->
    if (task.name.contains("checkDebugAarMetadata") || task.name.contains("checkReleaseAarMetadata")) {
        task.enabled = false
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Library Scanner QR Code
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.zxing:core:3.5.1'

    // Core Native libv2ray
    implementation(name: 'libv2ray', ext: 'aar')
}
